[project]
name = "ratio-dbt-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-core>=1.9.3",
    "dbt-duckdb>=1.9.2",
]
