version: 2

sources:
  - name: raw_claims
    schema: raw_claims
    tables:
      - name: beneficiary_summaries
      - name: carrier_claims
      - name: inpatient_claims
      - name: outpatient_claims
      - name: rx_drug_events
