version: 2

sources:
  - name: raw_clinical
    schema: raw_clinical
    tables:
      - name: allergies
      - name: careplans
      - name: conditions
      - name: devices
      - name: encounters
      - name: imaging_studies
      - name: immunizations
      - name: medications
      - name: observations
      - name: organizations
      - name: patients
      - name: payer_transitions
      - name: payers
      - name: procedures
      - name: providers
      - name: supplies
  - name: raw_claims
    schema: raw_claims
    tables:
      - name: beneficiary_summaries_2008
      - name: beneficiary_summaries_2009
      - name: beneficiary_summaries_2010
      - name: carrier_claims
      - name: inpatient_claims
      - name: outpatient_claims
      - name: rx_drug_events
